name: first-workflow
run-name: instance
on: [push]

jobs:
  say-hello:
     runs-on: ubuntu-latest
     steps: 
       - name: echoing some information
         run: echo "Hello world"
       - name: Checkout
         uses: actions/checkout@v3.5.3
       - uses: actions/setup-python@v3.1.4
         with:
           python-version: "3.10"
       - run: python -m pip install Flask
       - run: python test.py
