name: first-workflow
run-name: instance
on: [push]

jobs:
 build:
  
   strategy:
    matrix:
     version: ["3.10.12"]
         
   runs-on: ubuntu-latest
   steps: 
#        - name: echoing some information
#          run: echo "Hello world"
       - name: Checkout
         uses: actions/checkout@v3.5.3
#        - uses: actions/setup-python@v3.1.4
#          with:
#            python-version: ${{matrix.version }} //job will run three times in different versions
#        - run: python -m pip install Flask
#        - run: python test.py


       - name: Log in to Docker Hub
         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
         with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Extract metadata (tags, labels) for Docker
         id: meta
         uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
         with:
           images: nnagarathna/testing

       - name: Build and push Docker image
         uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
         with:
           context: .
           file: ./Dockerfile
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}

       
 deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
   - run: echo "Deploying"
